version: "3"

services:
  urlshortener:
    container_name: urlshortener
    image: urlshortener
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis
    volumes:
      - ./:/usr/src/app

  redis:
    image: redis:6.0-alpine
    volumes:
      - .redis.cache:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - .postgres.cache:/var/lib/postgresql/data
